@echo off
setlocal

rem High-FPS preset (RTX + high-refresh camera path)
set FACE_FRAME_WIDTH=640
set FACE_FRAME_HEIGHT=480
set FACE_FRAME_FPS=120
set FACE_TARGET_LOOP_FPS=120
set FACE_JPEG_QUALITY=62
set FACE_FACE_INFERENCE_STRIDE=4
set FACE_FACE_INFERENCE_SCALE=0.65
set FACE_POSE_INFERENCE_STRIDE=6
set FACE_POSE_INFERENCE_SCALE=0.60
set FACE_ENABLE_SKELETON=0
set FACE_ENABLE_OBJECT_DETECTION=0
set FACE_ENABLE_OCR=0
set FACE_ANALYTICS_MAX_SIDE=640

python scripts\run_all_dashboards.py %*
